insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (1, 'Cori Chadwell', 4.0, 'cchadwell0@about.me', 'Hāsilpur', '4325770165');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (2, 'Grantham Masterton', 1.6, 'gmasterton1@yelp.com', 'Babakankalong', '3595383746');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (3, 'Devlen Bardill', 4.6, 'dbardill2@utexas.edu', 'Half Way Tree', '9805448475');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (4, 'Darius Vernham', 4.7, 'dvernham3@sina.com.cn', 'Ayamaru', '4861727115');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (5, 'Barclay Lecky', 3.0, 'blecky4@a8.net', 'Panagyurishte', '9963051389');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (6, 'Ajay Gussin', 3.0, 'agussin5@google.co.jp', 'Antony', '1525101776');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (7, 'Tresa Widdop', 0.1, 'twiddop6@addtoany.com', 'Jiangnan', '8018652685');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (8, 'Allen Spawton', 2.3, 'aspawton7@buzzfeed.com', 'Na Yong', '1347242136');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (9, 'Marley Guiducci', 2.7, 'mguiducci8@wisc.edu', 'Sala', '8778676467');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (10, 'Wendall Mashro', 3.3, 'wmashro9@squarespace.com', 'Kaem', '2568129442');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (11, 'Darice Chettle', 4.8, 'dchettlea@xrea.com', 'Kapakabisa', '6681405098');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (12, 'Cindee Clulee', 0.6, 'ccluleeb@studiopress.com', 'Koszyce Wielkie', '9584789659');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (13, 'Sashenka Skeats', 1.2, 'sskeatsc@howstuffworks.com', 'La Virgen', '4853970227');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (14, 'Melody Kelbie', 0.4, 'mkelbied@cyberchimps.com', 'Centenario', '5794504844');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (15, 'Park Cheverell', 1.2, 'pcheverelle@shareasale.com', 'Satuba', '5075046383');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (16, 'Carita Esch', 4.8, 'ceschf@boston.com', 'Vecumnieki', '1867313389');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (17, 'Constanta Vaskov', 1.0, 'cvaskovg@is.gd', 'Az Zuwaytīnah', '3385898705');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (18, 'Agnesse Bosomworth', 4.1, 'abosomworthh@histats.com', 'Kiyawa', '2062960022');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (19, 'Kalli McHaffy', 0.4, 'kmchaffyi@cyberchimps.com', 'Sobradinho', '8918596464');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (20, 'Carlie Winsor', 4.0, 'cwinsorj@netlog.com', 'Kyzyl', '1805330521');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (21, 'Kitty Rourke', 4.9, 'krourkek@exblog.jp', 'Monticello', '7634997125');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (22, 'Carolyne Bendall', 4.2, 'cbendalll@altervista.org', 'Tianqian', '3282027922');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (23, 'Dud Lathbury', 3.8, 'dlathburym@cornell.edu', 'Bồng Sơn', '2446257095');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (24, 'Horton Chander', 3.6, 'hchandern@yale.edu', 'Baranowo', '3133839475');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (25, 'Jennee Kinnin', 1.4, 'jkinnino@moonfruit.com', 'Le Kremlin-Bicêtre', '5179279164');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (26, 'Maryanne Baldree', 2.9, 'mbaldreep@gov.uk', 'Swindon', '9004696788');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (27, 'Glenine Vinten', 4.5, 'gvintenq@umn.edu', 'Lebedinovka', '5909676387');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (28, 'Joscelin Brydie', 2.3, 'jbrydier@skype.com', 'Bous', '4821319469');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (29, 'Dre Van der Velden', 2.4, 'dvans@google.pl', 'Penambangan', '6914808361');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (30, 'Ailsun Ewbanks', 1.2, 'aewbankst@uol.com.br', 'Klippan', '2615050856');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (31, 'Ernestine Micklem', 4.4, 'emicklemu@psu.edu', 'Rumburk', '6282348824');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (32, 'Hakeem Arnal', 2.9, 'harnalv@google.co.jp', 'Cilegi', '4345395616');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (33, 'Hyman Crowden', 3.9, 'hcrowdenw@naver.com', 'Liulin', '5038714945');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (34, 'Sidoney Baptiste', 2.5, 'sbaptistex@shutterfly.com', 'Tataouine', '3261923003');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (35, 'Ronica Fiddeman', 3.3, 'rfiddemany@histats.com', 'Vorontsovka', '7322910593');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (36, 'Elwin Egalton', 2.2, 'eegaltonz@posterous.com', 'Kungsbacka', '6454853053');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (37, 'Dani Keningley', 0.2, 'dkeningley10@prlog.org', 'Baise City', '2635740514');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (38, 'Audrye Ogg', 1.4, 'aogg11@slideshare.net', 'Lanyang', '3735325053');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (39, 'Pryce Jozwik', 0.0, 'pjozwik12@unicef.org', 'Van Nuys', '2138394824');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (40, 'Sigfrid Laise', 1.0, 'slaise13@ezinearticles.com', 'Bago', '2089889586');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (41, 'Dalila Meeks', 4.7, 'dmeeks14@storify.com', 'Eksjö', '3101605667');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (42, 'Ailey Tellesson', 4.8, 'atellesson15@cocolog-nifty.com', 'Banes', '9692565333');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (43, 'Barbette Cake', 0.5, 'bcake16@slashdot.org', 'Sosnovoborsk', '3193593006');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (44, 'Shirline Plunket', 3.1, 'splunket17@huffingtonpost.com', 'Santa Rita', '7715730711');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (45, 'Olivette Hackleton', 1.3, 'ohackleton18@yahoo.co.jp', 'Donglu', '6707616343');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (46, 'Abdel McCamish', 4.7, 'amccamish19@ftc.gov', 'Chochkan', '9202799441');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (47, 'Elva Hurche', 0.8, 'ehurche1a@pcworld.com', 'Tawau', '3026648977');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (48, 'Darill Skipp', 0.4, 'dskipp1b@bbc.co.uk', 'Jintang', '1646438073');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (49, 'Brigitta Vanderson', 1.2, 'bvanderson1c@spiegel.de', 'Fratar', '3889246070');
insert into usuario (idusuario, nombreusuario, puntajeusuario, correo, ciudad, telefono) values (50, 'Celene Andriessen', 0.6, 'candriessen1d@eventbrite.com', 'Jiesheng', '5345444568');
