# Generated by Django 4.0.4 on 2022-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_city_alter_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
