# Generated by Django 4.0.4 on 2022-05-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report_favorite_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='business_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.business', verbose_name='BusinessID'),
        ),
    ]
