# Generated by Django 4.0.4 on 2022-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_city_alter_business_city_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
