# Generated by Django 4.0.4 on 2022-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_business_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='thumbpath'),
        ),
    ]
