# Generated by Django 4.0.4 on 2022-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_business_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='static/main/images/biz_profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/main/images/user_profile'),
        ),
    ]
