# Generated by Django 4.0.4 on 2022-05-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_business_cover_picture_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
