# Generated by Django 4.0.4 on 2022-05-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_consult_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='telephone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='business_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.business', verbose_name='BusinessID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_support',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='occupation_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.occupationstatus', verbose_name='Ocupation'),
        ),
    ]
