# Generated by Django 4.0.4 on 2022-05-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_occupationstatus_alter_business_telephone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_support',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
