# Generated by Django 4.0.4 on 2022-05-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_report_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_support',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
