# Generated by Django 4.0.4 on 2022-06-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_report_report_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cover_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
